manifest:
    remotes:
        # zmk official
        - name: zmkfirmware
          url-base: https://github.com/zmkfirmware
          # bravekarma
        - name: caksoylar
          url-base: https://github.com/caksoylar
          # kyek / duckyb
        - name: m165437
          url-base: https://github.com/M165437
        - name: ItsToxsec
          url-base: https://github.com/ItsToxsec
    projects:
        - name: zmk
          remote: zmkfirmware
          revision: main
          import: app/west.yml
        - name: urchin-zmk-module
          remote: duckyb
          revision: main
        - name: nice-view-sly
          remote: ItsToxsec
          revision: main
    self:
        path: config
